# Generated by Django 3.2.7 on 2022-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebCompanyJobs',
            fields=[
                ('web_company_jobs_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_info_id', models.BigIntegerField()),
                ('job_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_location', models.TextField(blank=True, null=True)),
                ('apply_link', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
