# Generated by Django 3.2.7 on 2022-10-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcompanyjobs',
            old_name='job_id',
            new_name='eligibility',
        ),
        migrations.AlterField(
            model_name='webcompanyjobs',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
