# Generated by Django 3.2.7 on 2022-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_auto_20221028_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcompanyjobs',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
